--get me average salary of IT_PROG
SELECT AVG(salary)
from EMPLOYEES
WHERE JOB_ID ='IT_PROG';

--GET ME ALL JOB IDIES
SELECT DISTINCT JOB_ID FROM EMPLOYEES;

SELECT JOB_ID, AVG(SALARY), COUNT(*) ,SUM(SALARY)
FROM EMPLOYEES
GROUP BY JOB_ID ;

--get me job_id where their salary avarage more than 5k
SELECT JOB_ID, AVG(SALARY), COUNT(*) ,SUM(SALARY)
FROM EMPLOYEES
where SALARY>5000
GROUP BY JOB_ID ;

